version: '3.4'
services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27018:27017
        volumes:
            - C:/db:/data/db
        networks: 
            - mongo-compose-network
    #
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
          - mongo
        networks: 
            - mongo-compose-network
    #
    dinosaurmongoapi:
        image: dinosaurmongoapi
        restart: always
        depends_on:
            - mongo
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5050:5050'
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            MongoDB__Host: mongo
            ASPNETCORE_URLS: 'http://+:5050'
        networks: 
            - mongo-compose-network
        volumes:
            - '~/.vsdbg:/remote_debugger:rw'
 
networks: 
    mongo-compose-network:
        driver: bridge